### ISSUE TITLE
无法正确获取玩家名

### ISSUE THREAD

**Issue by HanYuCR** [LoosePrince/PF-GUGUBot#101]
### 当前问题和情况

见日志栏

### 想要的效果或它本该拥有的效果

—

### MCDR 版本号

2.13.2

### GUGUbot 版本号

1.8.1

### cq_qq_api 版本号

1.0.3

### 日志内容

先看消息⬇️
![IMG_2184](https://github.com/user-attachments/assets/085db9c5-5093-49f0-83af-1e12071051de)
再看后台⬇️
![IMG_2187](https://github.com/user-attachments/assets/f81bef3b-f3b4-47af-ba13-01f4a82cf887)
好像看不出什么，我手动输入list，输出⬇️
![IMG_2186](https://github.com/user-attachments/assets/dc4eb07f-51e8-4b19-9c44-c5df4536b20c)
核心为Mohist1.20.1
墨家的核心好像输出的都是中文（虽然可以改就是了）

**Comment by LoosePrince** [comment]
中文不予适配，请采用rcon连接

**Comment by HanYuCR** [comment]
了解

**Comment by XueK66** [comment]
> 中文不予适配，请采用rcon连接

rcon也不太行，我上re match叭

**Comment by HanYuCR** [comment]
emm，如果要修的话，还有一个地方，就是启动服务器的时候如果是中文则不会输出消息，切换成英文就有了

**Comment by XueK66** [comment]
> emm，如果要修的话，还有一个地方，就是启动服务器的时候如果是中文则不会输出消息，切换成英文就有了

这个估计是MCDR解析启动日志的时候没考虑过中文，所以不会触发启动的 代码？这个的话就难搞了

**Comment by XueK66** [comment]
#102 服务器状态应该正常了
