### ISSUE TITLE
[增强] 上下线通知时排除假人

### ISSUE THREAD

**Issue by LoosePrince** [LoosePrince/PF-GUGUBot#108]
**当前情况：**
> 当前的情况
```
无法区分假人和真人玩家
```
 **预期效果：**
 > 想要的效果
```
上下线通知时排除假人
```

**Comment by XueK66** [comment]
v1.9.0 中实现
- [add bot notice switch](https://github.com/LoosePrince/PF-GUGUBot/commit/39a6f80cb4aadba9112141644282ab45399665fa)
