### ISSUE TITLE
[增强]群命令增加绑定管理相关命令

### ISSUE THREAD

**Issue by Dreamwxz** [LoosePrince/PF-GUGUBot#115]
**当前情况：**
> 当前的情况
```
绑定相关的管理命令需要通过私聊发送
```
 **预期效果：**
 > 想要的效果
```
#绑定 @别人 解绑或者换绑
以方便进行管理
```

**Comment by XueK66** [comment]
v1.9.0 中解决 
- [reconstruct bound system](https://github.com/LoosePrince/PF-GUGUBot/commit/2e23e898cce6e4f5fb2de36bd703728794f5a34e)
- [fix bound errors](https://github.com/LoosePrince/PF-GUGUBot/commit/40c0defcd25fbcda39850b99d0c5d3821f378eed)
