### ISSUE TITLE
[重构] 在特定项目完成前进行重构代码和次版本迭代（1.9.0）

### ISSUE THREAD

**Issue by LoosePrince** [LoosePrince/PF-GUGUBot#116]
在以下项目开始前完成代码重构

- https://github.com/LoosePrince/PF-GUGUBot/issues/106
- https://github.com/LoosePrince/PF-GUGUBot/issues/107

在代码重构时进行前需完成以下项目
- https://github.com/LoosePrince/PF-GUGUBot/issues/105
- https://github.com/LoosePrince/PF-GUGUBot/issues/109
- https://github.com/LoosePrince/PF-GUGUBot/issues/110
- https://github.com/LoosePrince/PF-GUGUBot/issues/111
- https://github.com/LoosePrince/PF-GUGUBot/issues/112
- https://github.com/LoosePrince/PF-GUGUBot/issues/113
- https://github.com/LoosePrince/PF-GUGUBot/issues/114
- https://github.com/LoosePrince/PF-GUGUBot/issues/115

重构要求
- 模块化代码，防止代码集中在一个文件中
- 结构清晰明了，便于拓展
- 主体代码文件仅负责调用，处理交予子模块/子模块文件

其他
- 重构后将迭代到下一个大版本 1.9.0

**Comment by XueK66** [comment]
v1.9.0 重构完成
https://github.com/LoosePrince/PF-GUGUBot/issues/112 暂时没解决
