### ISSUE TITLE
[增强] QQ机器人好友即管理员，支持私聊

### ISSUE THREAD

**Issue by LoosePrince** [LoosePrince/PF-GUGUBot#118]
**预期效果：**

允许开启好友管理模式，启用后QQ机器人的好友即为GUGUbot管理员，可以使用私聊的管理功能

 > 这曾为代办功能但是被忽略

在与 `GUGUweb` 对接后并不拥有 `超级管理员` 权限，但是可以通过私聊注册账号

**Comment by XueK66** [comment]
v1.9.3 中搞定啦！
- [friend is admin](https://github.com/LoosePrince/PF-GUGUBot/commit/b45ba7cc49c8ba4841fec127010237ae43c38bd6)
