### ISSUE TITLE
[增强] 允许自定义帮助提示，自动指令头

### ISSUE THREAD

**Issue by LoosePrince** [LoosePrince/PF-GUGUBot#120]
不再使用 `py文件` 储存帮助提示文件，使用单独的配置文件 `yml/json`
指令头使用 `#` 标记，在显示提示内容时会将 `#` 换成配置文件中自定义的指令头

**Comment by XueK66** [comment]
v1.9.3 中搞定啦！
- [customized help msg & auto command prefix](https://github.com/LoosePrince/PF-GUGUBot/commit/02cb9efb13e58848de7babfd05eebc12fcb3160e)
