### ISSUE TITLE
[增强] 转发显示来源群名称，添加点击复制

### ISSUE THREAD

**Issue by LoosePrince** [LoosePrince/PF-GUGUBot#121]
将简单的 `[QQ]` 更改为 群名称
如果可以，添加悬停显示QQ群号，点击复制群号。
示例：
`/tellraw <玩家选择器> {"text":"显示的文本","hoverEvent":{"action":"show_text","contents":"悬停时显示的文本"},"clickEvent":{"action":"copy_to_clipboard","value":"要复制的文本"}}`

 **当前情况：**
> 当前的情况
```
[QQ] [Shusao] 12313
```
 **预期效果：**
 > 想要的效果
```
[服务器一群] [Shusao] 12313
[服务器二群] [XueK__] 233
```

**Comment by XueK66** [comment]
v1.9.3 中搞定啦！
- [change to tellraw command with group_name appear](https://github.com/LoosePrince/PF-GUGUBot/commit/cd6d57ce0d299977d83a9045a1b33e28bcac1045)
