### ISSUE TITLE
加载异常

### ISSUE THREAD

**Issue by DavidBlackCN** [LoosePrince/PF-GUGUBot#22]
当加载插件后，无任何反应，无配置文件。
logs：

> [MCDR] [2023-08-28 19:05:35] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=gugubot@1.0.4,priority=1000,callback=<function on_load at 0x00000267B3CD77E0>]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 600, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\GUGUbot.mcdr\gugubot\__init__.py", line 35, in on_load
    qq_bot = qbot(server, config, data, host, port)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "plugins\GUGUbot.mcdr\gugubot\bot.py", line 35, in __init__
    self.loading_dicts()
  File "plugins\GUGUbot.mcdr\gugubot\bot.py", line 40, in loading_dicts
    self.font = pygame.font.Font(self.config["dict_address"]["font_path"], 26)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by DavidBlackCN** [comment]
MCDR=2.10.2
QQAPI=1.3.1
GUGUbot=1.0.4
coolqAPI=0.2.0

**Comment by LoosePrince** [comment]
已收到您的报错信息，请耐心等待解决和回复

**Comment by LoosePrince** [comment]
#### 可尝试在
1. - config\GUGUBot
> 下载 [config.yml](https://github.com/LoosePrince/PF-GUGUBot/blob/main/config_default.yml) 配置文件放置于此并修改其中的内容
2. - config\GUGUBot\fonts
> 下载 [MicrosoftYaHei-01.ttf](https://github.com/LoosePrince/PF-GUGUBot/blob/main/GUGUbot/font/MicrosoftYaHei-01.ttf) 字体文件放置其中
#### 诺以上两种方法无法解决请等待后续的修复

**Comment by XueK66** [comment]
已经定位到问题所在，马上修复

**Comment by DavidBlackCN** [comment]
这是什么中国速度（）

**Comment by XueK66** [comment]
main分支更新完毕，如有问题就继续提issue，谢谢反馈！

**Comment by DavidBlackCN** [comment]
> #### 可尝试在
> 1. `config\GUGUBot`
> 
> > 下载 [config.yml](https://github.com/LoosePrince/PF-GUGUBot/blob/main/config_default.yml) 配置文件放置于此并修改其中的内容
> 
> 2. `config\GUGUBot\fonts`
> 
> > 下载 [MicrosoftYaHei-01.ttf](https://github.com/LoosePrince/PF-GUGUBot/blob/main/GUGUbot/font/MicrosoftYaHei-01.ttf) 字体文件放置其中
> 
> #### 诺以上两种方法无法解决请等待后续的修复

已尝试，仍如上。

**Comment by XueK66** [comment]
> 也许并没有完全修复 已使用1h前发布的release，配置文件能正常加载，其余一切仍无法正常运行。 尝试了gocqhttp的反向ws和https连接，无响应。 logs：
> 
> > [MCDR] [2023-08-28 21:25:03] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=gugubot@1.0.4,priority=1000,callback=<function on_load at 0x000001D59E959D00>]
> > Traceback (most recent call last):
> > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 600, in trigger_listener
> > listener.execute(listener.plugin.server_interface, *args)
> > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
> > return self.callback(*args, **kwargs)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "plugins\GUGUbot.mcdr\gugubot__init__.py", line 35, in on_load
> > qq_bot = qbot(server, config, data, host, port)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > File "plugins\GUGUbot.mcdr\gugubot\bot.py", line 35, in **init**
> > self.loading_dicts()
> > File "plugins\GUGUbot.mcdr\gugubot\bot.py", line 40, in loading_dicts
> > self.font = pygame.font.Font(self.config["dict_address"]["font_path"], 26)
> > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > FileNotFoundError: No file './plugins/GUGUbot/font/MicrosoftYaHei-01.ttf' found in working directory 'C:\Users\Administrator\Desktop\MDS Union[MAIN]MDS Union\Survival-20230809'.
> 
> 看来和修复前一样呢（）

嗷，之前没看到最后一行报错，马上修，5min

**Comment by XueK66** [comment]
> > 也许并没有完全修复 已使用1h前发布的release，配置文件能正常加载，其余一切仍无法正常运行。 尝试了gocqhttp的反向ws和https连接，无响应。 logs：
> > > [MCDR] [2023-08-28 21:25:03] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=gugubot@1.0.4,priority=1000,callback=<function on_load at 0x000001D59E959D00>]
> > > Traceback (most recent call last):
> > > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 600, in trigger_listener
> > > listener.execute(listener.plugin.server_interface, *args)
> > > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python311\Lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
> > > return self.callback(*args, **kwargs)
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > File "plugins\GUGUbot.mcdr\gugubot__init__.py", line 35, in on_load
> > > qq_bot = qbot(server, config, data, host, port)
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > File "plugins\GUGUbot.mcdr\gugubot\bot.py", line 35, in **init**
> > > self.loading_dicts()
> > > File "plugins\GUGUbot.mcdr\gugubot\bot.py", line 40, in loading_dicts
> > > self.font = pygame.font.Font(self.config["dict_address"]["font_path"], 26)
> > > ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > > FileNotFoundError: No file './plugins/GUGUbot/font/MicrosoftYaHei-01.ttf' found in working directory 'C:\Users\Administrator\Desktop\MDS Union[MAIN]MDS Union\Survival-20230809'.
> > 
> > 
> > 看来和修复前一样呢（）
> 
> 嗷，之前没看到最后一行报错，马上修，5min

看了看，可以手动把/config/GUGUbot/config.yml里面的 `font_path` 换成 `./config/GUGUbot/MicrosoftYaHei-01.ttf`

**Comment by XueK66** [comment]
这个是包装的时候，默认路径忘记修改了

**Comment by DavidBlackCN** [comment]
> 

然后在config手动给一份font？
已尝试，无报错，其余配置文件正常生成，等待进一步测试

**Comment by XueK66** [comment]
> > 
> 
> 然后在config手动给一份font？ 已尝试，无报错，其余配置文件正常生成，等待进一步测试

好滴，谢谢反馈哦！

**Comment by DavidBlackCN** [comment]
一个小疑问
前置插件同时使用了coolqAPI和QQAPI，在配置与gocqhttp的连接时插件会选择使用谁的配置？
（可能歪issue了见谅XD）

**Comment by XueK66** [comment]
> 一个小疑问 前置插件同时使用了coolqAPI和QQAPI，在配置与gocqhttp的连接时插件会选择使用谁的配置？ （可能歪issue了见谅XD）

问题不大，这个插件用的是coolqAPI, QQAPI没有用到

**Comment by DavidBlackCN** [comment]
所以仅支持https连接？（coolqAPI没有反向ws）

**Comment by XueK66** [comment]
> 所以仅支持https连接？（coolqAPI没有反向ws）

对，懒狗腐竹直接把QQAPI的设置说明般过来了，等会我改一改

**Comment by XueK66** [comment]
> 一个小疑问 前置插件同时使用了coolqAPI和QQAPI，在配置与gocqhttp的连接时插件会选择使用谁的配置？ （可能歪issue了见谅XD）

注意修改一下下CoolQAPI的 `command_prefix` -> `'#'`
不然可能接处理不了命令

**Comment by XueK66** [comment]
> 你怎么知道我刚想问指令无效的问题（）

都是配置的坑，这些按理来说README上该写的，我们的问题，有其他问题的话可以加群：726741344
