### ISSUE TITLE
已知问题

### ISSUE THREAD

**Issue by XueK66** [LoosePrince/PF-GUGUBot#26]
- qq到mc：@ 有可能不会被成功转码
- qq到mc：容易出现（名字不匹配问题）

**Comment by DavidBlackCN** [comment]
问题1目前测试复现率0%
问题2目前复现率100%

**Comment by LoosePrince** [comment]
你们加油
![QN{GN7 }VSPZ A11_)WF038](https://github.com/LoosePrince/PF-GUGUBot/assets/107794785/21214e63-2bb2-4ea0-a645-87a4581222ca)

**Comment by DavidBlackCN** [comment]
新问题汇总：
1.自定义文字转图片长度
预期：默认150，可通过config自行修改

2.qq to mc的“（名字不匹配）”状态
预期：在群昵称与绑定ID不相同时显示，诱导玩家自行同步群昵称

3.假人识别
预期：可正确识别假人和真实玩家

4.提示绑定信息修正
预期：在未绑定玩家发言时正常提示其进行绑定

5.在线玩家
预期：当0人在线时显示0人在线，包括指令输出和动态群昵称同步

**Comment by DavidBlackCN** [comment]
提议/enchantment：
1.精简在线人数获取，将#玩家 和#假人 合并为一条指令。
2.重新规整消息格式，可参考[qqchat](https://github.com/MCDReforged/PluginCatalogue/blob/catalogue/plugins/qq_chat/readme-zh_cn.md)的list.

例子：
> QQ：#玩家
Bot：在线玩家数量为4，列表如下：
— — — — — — — —
玩家：
David_Black_
David_White_
假人：
Alex
hsds

**Comment by LoosePrince** [comment]
> 新功能或修改提议请单开issue，此条不采纳
