### ISSUE TITLE
[增强]长期更新计划请求(v1.1.0)

### ISSUE THREAD

**Issue by DavidBlackCN** [LoosePrince/PF-GUGUBot#39]
二次魔改希望以后能见到的功能：
注：这里的计划不一定能全部实现，如果官方确认不会追加，我可能将会自己fork一份实现部分功能
注2：大部分请求其实就是新版本[qqchat](https://github.com/AnzhiZhang/MCDReforgedPlugins/tree/master/qq_chat)的功能移植

1. 使用新的QQAPI，以同时支持https和反向ws协议（https有时会带来一些玄学问题）
2. 权限追加，可分流为主群和管理群，主群保留目前状态，管理器成员获得所有bot管理权限
3. 将指令前缀改为可在config自定义选项

**Comment by LoosePrince** [comment]
> 1. 使用新的QQAPI，以同时支持https和反向ws协议（https有时会带来一些玄学问题）
> 2. 权限追加，可分流为主群和管理群，主群保留目前状态，管理器成员获得所有bot管理权限
> 3. 将指令前缀改为可在config自定义选项

**这些将有可能在后续的更新中完成**
<br>

> 1. 使用新的QQAPI，以同时支持https和反向ws协议（https有时会带来一些玄学问题）

**这项因适配难度较高更新计划可能比较靠后**

**Comment by XueK66** [comment]
目前进度:

- [ ] 使用新的QQAPI，以同时支持https和反向ws协议（https有时会带来一些玄学问题）
- [ ] 权限追加，可分流为主群和管理群，主群保留目前状态，管理器成员获得所有bot管理权限
- [ ] 将指令前缀改为可在config自定义选项

**Comment by XueK66** [comment]
> 目前进度:
> 
> * [ ]  使用新的QQAPI，以同时支持https和反向ws协议（https有时会带来一些玄学问题）
> * [x]  权限追加，可分流为主群和管理群，主群保留目前状态，管理器成员获得所有bot管理权限
> * [x]  将指令前缀改为可在config自定义选项

把#36完成测试后，新开个v1.0.6-qqapi的分支慢慢整迁移

**Comment by XueK66** [comment]
已经在 #56 中切换成正向websocket协议

**Comment by XueK66** [comment]
所有建议及问题已解决 #66 感谢建议和反馈！
