### ISSUE TITLE
提交Issue的说明

### ISSUE THREAD

**Issue by LoosePrince** [LoosePrince/PF-GUGUBot#43]
### 1. 分离各种情况下的内容

> 例如把BUG和增加新功能进行分离，每个彼此关联不大的内容进行分离
> 分离的意思是指单开一个Issue

### 2. 为你的内容添加Tag

> 在右边的 `Labels` 可以选择符合你内容的标签（Tag），请尽可能的符合

### 3. 使你的内容更加易读

> [MD](https://docs.github.com/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax) 提供了各种各样的样式，请使用这些样式让你的内容更加美观

### 4. 规范你要提交的内容

> 在提交BUG和想要增加的内容时请明确你想要的效果和它目前的效果
> 可以使用以下格式
> 
> ```
> BUG：当前问题和情况
> 预期效果：想要的效果或者它本该拥有的效果
> ```

> 附上你的MCDR及插件版本号
> 
> ```
> MCDR=2.10.2
> GUGUbot=1.0.4
> coolqAPI=0.2.0
> ```

> 日志内容
> 
> ```
> [MCDR] [00:07:29] [TaskExecutor/ERROR]: Error invoking listener EventListener[plugin=gugubot@1.0.4,priority=1000,callback=<bound method qbot.addTextToImage.<locals>._addTextToImage of <gugubot.bot.qbot object at 0x0000024D31A76070>>]
> Traceback (most recent call last):
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\mcdreforged\plugin\plugin_manager.py", line 599, in trigger_listener
>     listener.execute(listener.plugin.server_interface, *args)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\mcdreforged\plugin\plugin_event.py", line 106, in execute
>     return self.callback(*args, **kwargs)
>   File "plugins\GUGUbot.mcdr\gugubot\bot.py", line 92, in _addTextToImage
>     try:
>   File "plugins\GUGUbot.mcdr\gugubot\bot.py", line 588, in send_msg_to_mc
>     if str(qq_id) in self.data:
> AttributeError: 'NoneType' object has no attribute 'groups'
> ```

### 6. 更多内容请等待补全...

**Comment by Ftimever** [comment]
The issue template could be simplified with elements like dropdowns.
