### ISSUE TITLE
主副账号管理方案（v1.x.0）

### ISSUE THREAD

**Issue by LoosePrince** [LoosePrince/PF-GUGUBot#45]
关于 #36  的补充

## 主账号
- 主账号功能和效果不变

### 功能配置
- 配置文件新增选项 `副账号` 功能，开关 为 `true`开 - `false`关，默认为 `false`
- 配置文件新增选项 `解绑主ID时同时取消该ID白名单` 功能，开关 为 `true`开 - `false`关，默认为 `false`
- 配置文件新增选项 `解绑副ID时同时取消该ID白名单` 功能，开关 为 `true`开 - `false`关，默认为 `false`
- 配置文件新增选项 `可绑定副账号数` 功能，可填项为数量，默认为 `1` ，大于数量时提示`您已绑定*个副账号，无法继续申请`

### ID绑定
- 在群内发送 `#申请副ID 游戏ID` 以申请副ID绑定
- 申请信息 `申请人昵称、QQ和申请ID` 将发至管理员私聊等待管理员的 `同意` 或 `拒绝`
- `副账号ID` 将通过 #36 中绑定离线账号的方式进行绑定，该方法通过 `uuid` 进行绑定无 `正版` 或 `离线` 的区别
- 不能绑定已绑定有的ID和白名单ID
- 副账号不能在未绑定主账号时直接申请绑定
- 绑定副账号ID时不会自动修改群昵称

### ID解绑
- 管理员私聊机器人 #解绑 游戏ID 可解绑该ID与QQ号的绑定，如果 `解绑副ID时同时取消该ID白名单` 开启则同时失去副ID的白名单，失去白名单时如果在线将被踢出 `kick` 服务器
- 解绑主ID则留空主ID的绑定，副账号不会顶替主账号，解绑副ID则留空副ID，主ID绑定不变
- 直接解绑QQ将同时失去主账号和副账号的绑定

### ID数据储存
将从旧配置升级为新配置，具体格式可能会存在变化，以实际显示或更新内容为准
```json
{
    "123456": ["player1","player2"],
// 主账号+副账号
    "123457": ["","player4"],
// 仅副账号
    "123458": ["player1"],
// 无副账号
}
```

### 转发时的ID显示
- 优先显示主ID

### 查询
- 绑定列表将显示副账号，使用逗号隔开，主账号在前，副账号在后

**Comment by LoosePrince** [comment]
追加副账户登录服务器条件，需要和主账号最近登录使用的IP一致，如未绑定主账号则不予登录（保障安全性）
方案一：解绑主账号时同时取消两个ID白名单，直到绑定主账号
方案二：解绑主账号时ban掉副账号，直到主账号绑定时解除（暂未想到不同处的实际用途，可能就多能设置一个提示语？）

**Comment by XueK66** [comment]
根据 #76 现在绑定变为可选项，绑定逻辑可以改一改哩

**Comment by LoosePrince** [comment]
> 根据 #76 现在绑定变为可选项，绑定逻辑可以改一改哩

绑定逻辑并未提及是否转发，关闭绑定也不影响绑定逻辑，而且此逻辑仅限启用绑定的情况

**Comment by XueK66** [comment]
v1.8 新增了绑定多个账号的功能 config中可以自行设定数量（默认为1）

不采用主副账号机制（小众 + 机制复杂）
