### ISSUE TITLE
插件加载但未出现配置文件

### ISSUE THREAD

**Issue by DreamYi233** [LoosePrince/PF-GUGUBot#49]
[MCDR.log](https://github.com/LoosePrince/PF-GUGUBot/files/14524465/MCDR.log)
插件加载未出现配置文件
出现错误Error invoking listener EventListener[plugin=gugubot@1.0.6,priority=1000,callback=<function on_server_startup at 0x000001DB1CD91FC0>]
Traceback (most recent call last):

**Comment by LoosePrince** [comment]
由于未知原因导致创建配置文件失败，可尝试下载配置文件 [config.json](https://github.com/LoosePrince/PF-GUGUBot/blob/main/config_default.yml) 放置于 `./config/GUGUBot/config.json` 文件夹内然后重启插件重试，这应该可以解决你的问题，至于创建失败的问题可能需要额外的排查

**Comment by LoosePrince** [comment]
由 #50 完成
