### ISSUE TITLE
加载插件时在config\GUGUbot文件夹中不会自动下载字体,需要手动补全

### ISSUE THREAD

**Issue by Mxmilu666** [LoosePrince/PF-GUGUBot#5]
如题
需要手动提取windows中的MicrosoftYaHei并添加到config\GUGUbot\fonts文件夹才可以正常启动
不然会报错

**Comment by XueK66** [comment]
- [TODO]: 字体路径问题

**Comment by XueK66** [comment]
目前字体是用来解决长文本容易封控的问题，后续会优化滴！
- [ TODO ]：字体的路径问题，后续加入config设置中，并默认一个系统字体 

大学牲有空就更新！谢谢提Issue

**Comment by XueK66** [comment]
已经整合至1.0.3版 #10
