### ISSUE TITLE
文件夹未初始化导致的无法启动

### ISSUE THREAD

**Issue by Evander0** [LoosePrince/PF-GUGUBot#64]
环境：ubuntu server 22.04（无桌面环境）
MCDReforged 2.13.1
GUGUbot-v1.1.1

[MCDR] [2024-08-17 18:07:16.615] [MainThread/INFO] [mcdr_server.py:615(__on_mcdr_start)]: MCDReforged 2.13.1 正在启动
[MCDR] [2024-08-17 18:07:16.618] [MainThread/INFO] [python_plugin.py:36(load)]: MCDReforged 正于 Python 3.10.12 环境中运行
[MCDR] [2024-08-17 18:07:16.629] [TaskExecutor/INFO] [meta_holder.py:202(__load_cached_file)]: 已从缓存文件加载插件仓库元数据 (更新于 2024-08-17 17:53:05)
[MCDR] [2024-08-17 18:07:16.630] [TaskExecutor/INFO] [plugin_manager.py:693(refresh_all_plugins_action)]: 刷新所有插件中
[MCDR] [2024-08-17 18:07:16.641] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 cq_qq_api@1.0.0 已加载
[MCDR] [2024-08-17 18:07:16.642] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 crash_restart@1.0.0 已加载
[MCDR] [2024-08-17 18:07:16.655] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 gugubot@1.1.1 已加载
[MCDR] [2024-08-17 18:07:16.655] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 offline_whitelist_reforged@1.1.0 已加载
[MCDR] [2024-08-17 18:07:16.656] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 online_player_api@1.0.0 已加载
[MCDR] [2024-08-17 18:07:16.659] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 prime_backup@1.6.3 已加载
[MCDR] [2024-08-17 18:07:16.660] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 simple_test@3.0.0 已加载
[MCDR] [2024-08-17 18:07:16.661] [TaskExecutor/INFO] [plugin_manager.py:217(__load_plugin)]: 插件 start_stop_helper_r@0.1.0 已加载
[MCDR] [2024-08-17 18:07:17.77] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [cq_qq_api]: 配置文件已加载
[MCDR] [2024-08-17 18:07:17.77] [TaskExecutor/INFO] [websocket.py:24(connect)] [cq_qq_api]: Try to connect ws://192.168.5.2:3002/
[MCDR] [2024-08-17 18:07:17.78] [TaskExecutor/INFO] [websocket.py:36(connect)] [cq_qq_api]: ~~ Start connection to ws://192.168.5.2:3002/ ~~
[MCDR] [2024-08-17 18:07:17.78] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [crash_restart]: 配置文件已加载
[MCDR] [2024-08-17 18:07:17.78] [TaskExecutor/INFO] [__init__.py:56(on_load)] [crash_restart]: Config info: {'MAX_COUNT': 3, 'COUNTING_TIME': 300}
[MCDR] [2024-08-17 18:07:17.80] [TaskExecutor/WARNING] [websocket.py:64(send_message)] [cq_qq_api]: Websocket disconnect!
[MCDR] [2024-08-17 18:07:21.500] [TaskExecutor/ERROR] [plugin_manager.py:739(trigger_listener)]: Error invoking listener EventListener(plugin='gugubot@1.1.1', callback=<function on_load at 0x7df684632b00>, priority=1000)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/plugin/plugin_manager.py", line 737, in trigger_listener
    listener.execute(listener.plugin.server_interface, *args)
  File "/usr/local/lib/python3.10/dist-packages/mcdreforged/plugin/plugin_event.py", line 106, in execute
    return self.callback(*args, **kwargs)
  File "plugins/GUGUbot-v1.1.1.mcdr/gugubot/__init__.py", line 42, in on_load
    qq_bot = qbot(server, config, data, cq_qq_api_bot)
  File "plugins/GUGUbot-v1.1.1.mcdr/gugubot/bot.py", line 39, in __init__
    self.loading_dicts()
  File "plugins/GUGUbot-v1.1.1.mcdr/gugubot/bot.py", line 44, in loading_dicts
    self.packing_copy()
  File "plugins/GUGUbot-v1.1.1.mcdr/gugubot/bot.py", line 779, in packing_copy
    __copyFile("gugubot/data/bound.jpg", "./config/GUGUbot/bound.jpg")        # 绑定图片
  File "plugins/GUGUbot-v1.1.1.mcdr/gugubot/bot.py", line 777, in __copyFile
    with open(target_path, 'wb') as f:                        # 复制文件
FileNotFoundError: [Errno 2] No such file or directory: './config/GUGUbot/bound.jpg'
[MCDR] [2024-08-17 18:07:21.502] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [offline_whitelist_reforged]: 配置文件已加载
[MCDR] [2024-08-17 18:07:21.505] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [prime_backup]: 配置文件已加载
[MCDR] [2024-08-17 18:07:21.513] [PB@7f6d-worker-heavy/INFO] [task_manager.py:90(__task_loop)] [prime_backup]: Worker heavy started
[MCDR] [2024-08-17 18:07:21.514] [PB@7f6d-worker-light/INFO] [task_manager.py:90(__task_loop)] [prime_backup]: Worker light started
[MCDR] [2024-08-17 18:07:21.514] [PB@7f6d-crontab-scheduler/INFO] [base.py:181(start)] [prime_backup]: Scheduler started
[MCDR] [2024-08-17 18:07:21.514] [TaskExecutor/INFO] [base.py:895(_real_add_job)] [prime_backup]: Added job "CreateDbBackupJob.run" to job store "default"
[MCDR] [2024-08-17 18:07:21.515] [TaskExecutor/INFO] [base.py:895(_real_add_job)] [prime_backup]: Added job "PruneBackupJob.run" to job store "default"
[MCDR] [2024-08-17 18:07:21.515] [TaskExecutor/INFO] [base.py:895(_real_add_job)] [prime_backup]: Added job "ScheduledBackupJob.run" to job store "default"
[MCDR] [2024-08-17 18:07:21.515] [TaskExecutor/INFO] [base.py:895(_real_add_job)] [prime_backup]: Added job "VacuumSqliteJob.run" to job store "default"
[MCDR] [2024-08-17 18:07:21.517] [TaskExecutor/INFO] [plugin_server_interface.py:277(log)] [start_stop_helper_r]: 配置文件已加载
[MCDR] [2024-08-17 18:07:21.517] [TaskExecutor/INFO] [mcdr_server.py:294(load_plugins)]: 共加载: §78§r 个插件; 已加载插件数: §710§r

**Comment by Evander0** [comment]
问题出在从包中拷贝出bound.jpg和字体文件处
修改代码尝试修复无果

**Comment by LoosePrince** [comment]
尝试下载[bound.jpg](https://github.com/LoosePrince/PF-GUGUBot/blob/main/GUGUbot/gugubot/data/bound.jpg)和[MicrosoftYaHei-01.ttf](https://github.com/LoosePrince/PF-GUGUBot/blob/main/GUGUbot/gugubot/font/MicrosoftYaHei-01.ttf)

放置于如下路径
config/
- GUGUBot/
- - MicrosoftYaHei-01.ttf
- - bound.jpg

**Comment by XueK66** [comment]
抱歉哩！
错误原因：初始化文件的时候未考虑到初始化相关文件夹
修复方法：添加文件夹检测及创建功能 #65
再次感谢！
