### ISSUE TITLE
将gugubot放入mcdr中plugins文件夹后，mcdr重载并不会加载gugubot

### ISSUE THREAD

**Issue by zhanghx013579** [LoosePrince/PF-GUGUBot#7]
而且原版的coolqapi是可以用的，但是用为插件修改的coolqapi就会崩服务端，无法使用
在检查已加载mcdr插件目录时，除gugubot以外，其他qpi均加载，且配置好go-cqhttp后可以正常连接coolqapi，找到上传http

**Comment by LoosePrince** [comment]
请提交一下日志

**Comment by zhanghx013579** [comment]
[2023-08-10-30.zip](https://github.com/LoosePrince/PF-GUGUBot/files/12354388/2023-08-10-30.zip)

**Comment by LoosePrince** [comment]
![image](https://github.com/LoosePrince/PF-GUGUBot/assets/107794785/a5429b74-8586-4787-9925-c4ae109cdd93)
根据报错内容，原因是`Python依赖库`需要`blinker`库的版本大于等于`1.6.2`，但是当前安装的版本是`1.5`。解决方法是升级blinker库到1.6.2或更高版本
可以通过使用pip命令来升级blinker库。在命令行中输入以下命令即可升级到最新版本：
`pip install --upgrade blinker`
如果还有问题可以继续此问题

**Comment by zhanghx013579** [comment]
好的，谢谢up啦，我待会试试，有问题接着来问哈
