### ISSUE TITLE
Request New Features:Bypass the binding and forward the game directly.

### ISSUE THREAD

**Issue by Seungmin922** [LoosePrince/PF-GUGUBot#76]
请求新功能:绕过绑定，直接转发游戏.
Such as the title.
如标题.

**Comment by LoosePrince** [comment]
添加方案：
添加开关项
1.关闭绑定（侧底关闭绑定，转发也不再显示未绑定）
2.略过强制绑定（允许未绑定的转发）

**Comment by XueK66** [comment]
1.1.6 中增强了 bound_notice 的判定范围，允许未绑定进行转发操作

[bound change to optional operation](https://github.com/LoosePrince/PF-GUGUBot/commit/de203cb38e0b56bd08e6d9f968f221c4a0a76e10)
