### ISSUE TITLE
!! No forwarding.Such as:!!qb list

### ISSUE THREAD

**Issue by Seungmin922** [LoosePrince/PF-GUGUBot#77]
!! No forwarding.Is it designed on purpose? If it is, add a switch.
!!没有转发,是特意设计吗？如果不是，请添加开关.
如:!!qb list.

**Comment by LoosePrince** [comment]
添加方案：
添加开关项
1.转发指令（转发!!开头的消息）

**Comment by XueK66** [comment]
1.1.6 新增转发开关

[Add mc command forward option](https://github.com/LoosePrince/PF-GUGUBot/commit/1756be256425f8b6889a48da6fa2fba55cb6e814)
