### ISSUE TITLE
[增强] 过滤无关群聊消息

### ISSUE THREAD

**Issue by LoosePrince** [LoosePrince/PF-GUGUBot#79]
> 在提交想要增加的内容时请明确你想要的效果和它目前的效果
> 使用以下格式

 **当前情况：**
> 当前的情况
```
显示全部
```
 **预期效果：**
 > 想要的效果

过滤掉非指定群的消息，即不在终端展示和处理
增加允许关闭在终端展示群聊内容（默认展示群聊内容至终端）

 **MCDR及插件版本号**
 
 ```
 MCDR=
 GUGUbot=1.1.5
 cq-qq-api=1.0.1
 ```

**Comment by XueK66** [comment]
在 1.1.6 版本中实现 

[Filter irrelavent message & add config for showing report message](https://github.com/LoosePrince/PF-GUGUBot/commit/292ead1a1c1b1119b3972d8555446d118a669814)
