### ISSUE TITLE
[增强 1.7.0 & 1.8.0]

### ISSUE THREAD

**Issue by MSNLING** [LoosePrince/PF-GUGUBot#83]
**当前情况：**
> 当前的情况
- 玩家列表逻辑有点问题。
- 无法用机器人给服务器发送指令
- 无图片识别功能
- 无玩家进出场通知
- 无法显示群内公告
- 无关机通知
 **预期效果：**
 > 想要的效果
- 机器人运行指令（私聊机器人或者群内直接发）
- 发图片链接（配合mod：ChatImang）
- 改改玩家列表的逻辑（比如开着绑定系统，可以选择不开绑定通知，然后服务器开启白名单，这样大伙就强行绑定了游戏id，玩家列表就能正常识别正确是玩家并且显示在机器人的昵称上。）
- 增加玩家进出场的通知
- 增加显示群内公告
- 增加关机通知
- 可以在游戏里@群成员或者在群内@服务器成员（在任务栏上显示）
- 可以增加点机器人的娱乐小功能（如果可以，这个小功能没有也无伤大雅）
- Mc TEAM 前缀识别与支持
- 在线人数定时刷新
- 新增：`清空` 功能 -> 清空白名单 + 绑定列表 （二次确认）
- 新增：`取消` 功能 -> 取消 添加图片 （30s自动取消）
- 新增：`重启` 功能 -> 自己重启
- 风格 切换增加 冷却 （管理员无视）
- 群功能失效 -> 只转发和管理员命令
 **MCDR及插件版本号**
 
 ```
 MCDR=2.13.2
 GUGUbot=1.1.6
 cq-qq-api=1.0.2
 ```

**Comment by LoosePrince** [comment]
> 改改玩家列表的逻辑（比如开着绑定系统，可以选择不开绑定通知，然后服务器开启白名单，这样大伙就强行绑定了游戏id，玩家列表就能正常识别正确是玩家并且显示在机器人的昵称上。）

> 可以在游戏里@群成员或者在群内@服务器成员（在任务栏上显示）

以上两条为已有功能，诺有问题将在下个版本修复它

**Comment by XueK66** [comment]
- 机器人运行指令（私聊机器人或者群内直接发）
  - 准备用 #执行 <命令> + rcon 返回解决
- 发图片链接（配合mod：ChatImang）
- 改改玩家列表的逻辑（比如开着绑定系统，可以选择不开绑定通知，然后服务器开启白名单，这样大伙就强行绑定了游戏id，玩家列表就能正常识别正确是玩家并且显示在机器人的昵称上。）
  - 考虑用IP区分假人和玩家
- 增加玩家进出场的通知
  - 增加进出场提示 + 开关
- 增加显示群内公告
- 增加关机通知
- 可以在游戏里@群成员或者在群内@服务器成员（在任务栏上显示）
- 可以增加点机器人的娱乐小功能（如果可以，这个小功能没有也无伤大雅）
- Mc TEAM 前缀识别与支持
- 在线人数定时刷新

**Comment by Redappleyyds** [comment]
能不能支持多服务器

**Comment by LoosePrince** [comment]
> 能不能支持多服务器

支持多服，如有其它需求请单开Issue

**Comment by XueK66** [comment]
> 能不能支持多服务器

细说多服，是多服转发，多服命令，还是其他东西？欢迎进群视奸交流或者提意见（最好的）！

**Comment by XueK66** [comment]
GUGUBot v1.8.0 已实现全部功能
