### ISSUE TITLE
机器人执行指令

### ISSUE THREAD

**Issue by MSNLING** [LoosePrince/PF-GUGUBot#89]
### 当前问题和情况

机器人无法执行私聊的指令

### 想要的效果或它本该拥有的效果

机器人执行私聊的指令

### MCDR 版本号

2.13.2

### GUGUbot 版本号

1.1.7

### cq_qq_api 版本号

1.0.2

### 日志内容

私聊后没反应
![c32d18150c1b018861ea9dbcb71627c9](https://github.com/user-attachments/assets/401e1efe-950f-4769-8a5c-e0c65e6ce0e1)
后台当成消息处理了
![image](https://github.com/user-attachments/assets/9537a475-b229-43ce-b0e1-c258fa4fa671)

**Comment by LoosePrince** [comment]
指令为`#执行 指令内容`
