### ISSUE TITLE
qq到mc无法使用

### ISSUE THREAD

**Issue by zhanghx013579** [LoosePrince/PF-GUGUBot#9]
[MCDR.log](https://github.com/LoosePrince/PF-GUGUBot/files/12365981/MCDR.log)
昨天用的时候可以从mc转发到qq群，但从qq中不论是输带井号的指令，群聊或是私聊都没用，都无法转发到服务器
今天用的时候mc转发到qq也用不了了

**Comment by zhanghx013579** [comment]
对了，而且魔改过的coolqapi一装在服务器上，mcdr就会崩，如果重启就直接崩服务端了

**Comment by zhanghx013579** [comment]
原版的coolqapi装上以后就可以正常使用

**Comment by LoosePrince** [comment]
![image](https://github.com/LoosePrince/PF-GUGUBot/assets/107794785/c3e77b05-819d-440f-9b5d-4467c3b23081)
原版coolqapi无法与1.0.2的机器人插件对接，如果魔改版的coolqapi无法运行请尝试旧版本或等待后续的修复

**Comment by XueK66** [comment]
看log里面5700端口拒绝访问，建议换一个端口试试？
可能是端口冲突导致gugubot启动不了

现在正在把魔改CoolQAPI的功能迁移到gugubot里面，以后就能用原版CoolQAPI勒，请耐心等待一会

**Comment by XueK66** [comment]
github仓库已更新，晚点会发布Release
