### ISSUE TITLE
[增强] 增加QQ表情和mface表情转换至游戏聊天栏

### ISSUE THREAD

**Issue by LoosePrince** [LoosePrince/PF-GUGUBot#92]
**当前情况：**
> 当前的情况
```
一律为 [表情]
```
 **预期效果：**
 > 想要的效果

增加QQ表情和mface表情
CQ码格式如下
QQ表情：`[CQ:face,id=277]` = ![image](https://github.com/user-attachments/assets/2864881c-f5c9-49ad-86a4-6aaf187565f0)
mface表情：
![37acec9c6ee2a741a9bb7bd9815892e9](https://github.com/user-attachments/assets/0c62c1f5-eba6-4e1f-9d33-ea326f5eabf3)
![88f0a0505ce483524e4cea606ca16145](https://github.com/user-attachments/assets/d025b38a-5a37-4e35-912c-e78aab470f62)
`[CQ:mface,summary=&#91;敲黑板&#93;,url=https://gxh.vip.qq.com/club/item/parcel/item/e2/e236bd3faf64e579678ec218df99fdba/raw300.gif,emoji_id=e236bd3faf64e579678ec218df99fdba,emoji_package_id=232743,key=c643d011575a7054]`

**Comment by XueK66** [comment]
#95 1.7.4 版本已解决
