### ISSUE TITLE
绑定提示并没有排除qq自带的bot

### ISSUE THREAD

**Issue by Dreamwxz** [LoosePrince/PF-GUGUBot#93]
### 当前问题和情况

当q群助手或者其他bot在q群中发言，会被绑定提示

### 想要的效果或它本该拥有的效果

这些bot或者消息应该被排除在绑定提示中

### MCDR 版本号

2.13.2

### GUGUbot 版本号

1.7.2

### cq_qq_api 版本号

1.0.2

### 日志内容

[MCDR] [09:52:33] [TaskExecutor/INFO] [gugubot]: 收到消息上报：2854196310:[CQ:json,data={"app":"com.tencent.autoreply"&#44;"config":{"ctime":1727949151&#44;"token":"c6207c4ge9eecebd613230eh285a440b"}&#44;"meta":{"metadata":{"buttons":&#91;{"action":"notify"&#44;"action_data":"服务器地址？"&#44;"name":"服务器地址？"&#44;"slot":1}&#44;{"action":"notify"&#44;"action_data":"服务器的版本？"&#44;"name":"服务器的版本？"&#44;"slot":2}&#93;&#44;"title":"猜你想问以下问题"&#44;"token":"kcWr5mFgVHlQBSQvyDOXZ3MXrgfHJRpJChRYfVKyCAQ="&#44;"type":"guest"}}&#44;"prompt":"自助问答"&#44;"ver":"0.0.0.1"&#44;"view":"autoreply"}

[MCDR] [2024-10-03 08:19:02.24] [TaskExecutor/INFO] [bot.py:701(send_msg_to_mc)] [gugubot]: 收到消息上报：3889060937:[CQ:at,qq=3512600973,name=laosepiqinsihuan]
请先领养机器人哦
使用“/开始养成”来领养一只丛雨吧！

**Comment by Seungmin922** [comment]
Do people who make machines usually have their QQ numbers published?
做机器的qq号一般会上吗？ @XueK66

**Comment by XueK66** [comment]
#94 1.7.3 已解决，谢谢哩！

**Comment by XueK66** [comment]
> Do people who make machines usually have their QQ numbers published? 做机器的qq号一般会上吗？ @XueK66

会有显示，可以通过私下绑定在 1.7.3 之前的版本解决这个问题。1.7.3 新增检测 官方群机器人功能 （is_robot属性），自动解决了。
