### ISSUE TITLE
无法正常获取玩家列表

### ISSUE THREAD

**Issue by HanYuCR** [LoosePrince/PF-GUGUBot#99]
### 当前问题和情况

见日志栏

### 想要的效果或它本该拥有的效果

正常显示在线玩家名

### MCDR 版本号

2.13.2

### GUGUbot 版本号

1.8.0

### cq_qq_api 版本号

1.0.3

### 日志内容

![IMG_2174](https://github.com/user-attachments/assets/82792f24-ddc3-4aa2-b2ed-f7f651e49cde)
⬆️芝士发的消息
![IMG_2175](https://github.com/user-attachments/assets/b9f86f16-ada0-4ad7-aac8-5bfb5de2e3b4)
⬆️芝士后台

**Comment by XueK66** [comment]
抱歉哩，请问一下下是什么端？

**Comment by XueK66** [comment]
我们截取 `list` 的返回来解析，问题跟 https://github.com/LazyAlienServer/Where2go/issues/12 类似。

现在用 `rcon` 和 `Online Player API` 来处理这个情况，麻烦尝试更新 `v1.8.1` 一下下试试效果。有问题的话欢迎提出！

**Comment by HanYuCR** [comment]
测试了最新版，已经解决了，感谢修复
另外提一嘴，这是1.7.10forge (笑)
因为某些原因不得不用这个

**Comment by XueK66** [comment]
> 测试了最新版，已经解决了，感谢修复 另外提一嘴，这是1.7.10forge (笑) 因为某些原因不得不用这个

好家伙，好古早的版本。
修复就行，有别的需求或者问题的话欢迎提哩！
